from antlr4 import Lexer


class AbstractSqlBaseLexer(Lexer):
    """
    Automatically generated by Antlr4.

    It was added originally in CrateDB (https://github.com/crate/crate/commit/8e7cfd7c4a05fc27de8ce71af9165b98c986d883)
    to implement $ strings, e.g: "SELECT $my friend's house$", we cannot do the same since it also generates invalid
    Python syntax:

    # SqlBaseLexer.py
    class SqlBaseLexer(AbstractSqlBaseLexer):
        ...


        def END_DOLLAR_QUOTED_STRING_sempred(...):
            if actionIndex == 1:
                pushTags()

                ^^^^^^^^^
    """

    pass
